### ISSUE TITLE
How do you confirm the value of alpha and scale?

### ISSUE THREAD

**Issue by UpCoder** [kensaem/SNN_selu#1]
I have a problem in your vgg_model.py.
How do you confirm the value of alpha and scale? Is that constant?
Thanks

**Comment by kensaem** [comment]
Hi, UpCoder.

Yes, it's constant values.
You can find them page #4 in the original paper.
To make SELU working correctly, it's important to normalizing input values.

**Comment by UpCoder** [comment]
Thank you very much!
